/**
 * Score storage behind an interface.
 *
 * The dev driver writes JSON and blobs to disk so the whole stack runs with
 * zero external services. Production (PLAN.md: Postgres + S3-compatible
 * object storage on CubCloud infra) implements the same interface; nothing
 * above this file changes.
 */
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import path from "node:path";

export interface SharedScore {
  id: string;
  title: string;
  artist: string;
  format: "gp" | "altex";
  /** alphaTex source, for scores that have one. */
  tex: string | null;
  /** Base64 of the original binary, for imported Guitar Pro files. */
  bytesB64: string | null;
  createdAt: number;
  /** Absent on shares created before accounts existed, or anonymously. */
  ownerId?: string;
}

export interface ScoreStore {
  put(record: SharedScore): Promise<void>;
  get(id: string): Promise<SharedScore | undefined>;
  delete(id: string): Promise<void>;
  listByOwner(ownerId: string): Promise<SharedScore[]>;
}

export interface User {
  id: string;
  email: string;
  passwordHash: string;
  createdAt: number;
}

export interface UserStore {
  byEmail(email: string): Promise<User | undefined>;
  byId(id: string): Promise<User | undefined>;
  put(user: User): Promise<void>;
}

export interface SessionStore {
  create(token: string, userId: string): Promise<void>;
  userIdFor(token: string): Promise<string | undefined>;
  destroy(token: string): Promise<void>;
}

/** A user's cloud library entry. Bytes travel as base64 in the JSON body. */
export interface CloudEntry {
  id: string;
  ownerId: string;
  title: string;
  artist: string;
  format: "gp" | "altex";
  tex: string | null;
  bytesB64: string | null;
  /** Semantic model JSON for scores authored or converted in CubScore. */
  core: string | null;
  report: string | null;
  authored: boolean;
  tracks: number;
  bars: number;
  addedAt: number;
  updatedAt: number;
}

export interface LibraryStore {
  put(entry: CloudEntry): Promise<void>;
  get(ownerId: string, id: string): Promise<CloudEntry | undefined>;
  list(ownerId: string): Promise<CloudEntry[]>;
  delete(ownerId: string, id: string): Promise<void>;
}

/** Unguessable id: share links are capability URLs until accounts land. */
export function newShareId(): string {
  return randomBytes(12).toString("base64url");
}

function assertSafeId(id: string): void {
  // Ids are generated by us, but never trust them as paths.
  if (!/^[A-Za-z0-9_-]{1,64}$/.test(id)) throw new Error("invalid id");
}

/** One JSON document per record in a directory. */
class JsonDir<T extends { id: string }> {
  constructor(private readonly dir: string) {}

  private fileFor(id: string): string {
    assertSafeId(id);
    return path.join(this.dir, `${id}.json`);
  }

  async put(record: T): Promise<void> {
    await mkdir(this.dir, { recursive: true });
    await writeFile(this.fileFor(record.id), JSON.stringify(record));
  }

  async get(id: string): Promise<T | undefined> {
    try {
      return JSON.parse(await readFile(this.fileFor(id), "utf8")) as T;
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") return undefined;
      if ((e as Error).message === "invalid id") return undefined;
      throw e;
    }
  }

  async delete(id: string): Promise<void> {
    try {
      await rm(this.fileFor(id));
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e;
    }
  }

  async all(): Promise<T[]> {
    let names: string[];
    try {
      names = (await readdir(this.dir)).filter((n) => n.endsWith(".json"));
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") return [];
      throw e;
    }
    const out: T[] = [];
    for (const name of names) {
      const record = await this.get(name.slice(0, -5));
      if (record) out.push(record);
    }
    return out;
  }
}

export class FileStore implements ScoreStore {
  private readonly docs: JsonDir<SharedScore>;

  constructor(dir: string) {
    this.docs = new JsonDir<SharedScore>(dir);
  }

  put(record: SharedScore): Promise<void> {
    return this.docs.put(record);
  }

  get(id: string): Promise<SharedScore | undefined> {
    return this.docs.get(id);
  }

  delete(id: string): Promise<void> {
    return this.docs.delete(id);
  }

  /** Linear scan; fine for the dev driver, an indexed query in production. */
  async listByOwner(ownerId: string): Promise<SharedScore[]> {
    const all = await this.docs.all();
    return all.filter((s) => s.ownerId === ownerId).sort((a, b) => b.createdAt - a.createdAt);
  }
}

export class FileUserStore implements UserStore {
  private readonly docs: JsonDir<User>;

  constructor(dir: string) {
    this.docs = new JsonDir<User>(dir);
  }

  put(user: User): Promise<void> {
    return this.docs.put(user);
  }

  byId(id: string): Promise<User | undefined> {
    return this.docs.get(id);
  }

  async byEmail(email: string): Promise<User | undefined> {
    const all = await this.docs.all();
    return all.find((u) => u.email === email);
  }
}

export class FileSessionStore implements SessionStore {
  private readonly docs: JsonDir<{ id: string; userId: string; createdAt: number }>;

  constructor(dir: string) {
    this.docs = new JsonDir(dir);
  }

  create(token: string, userId: string): Promise<void> {
    return this.docs.put({ id: token, userId, createdAt: Date.now() });
  }

  async userIdFor(token: string): Promise<string | undefined> {
    return (await this.docs.get(token))?.userId;
  }

  destroy(token: string): Promise<void> {
    return this.docs.delete(token);
  }
}

export class FileLibraryStore implements LibraryStore {
  constructor(private readonly dir: string) {}

  private dirFor(ownerId: string): JsonDir<CloudEntry> {
    assertSafeId(ownerId);
    return new JsonDir<CloudEntry>(path.join(this.dir, ownerId));
  }

  put(entry: CloudEntry): Promise<void> {
    return this.dirFor(entry.ownerId).put(entry);
  }

  get(ownerId: string, id: string): Promise<CloudEntry | undefined> {
    return this.dirFor(ownerId).get(id);
  }

  async list(ownerId: string): Promise<CloudEntry[]> {
    const all = await this.dirFor(ownerId).all();
    return all.sort((a, b) => b.updatedAt - a.updatedAt);
  }

  delete(ownerId: string, id: string): Promise<void> {
    return this.dirFor(ownerId).delete(id);
  }
}
