/**
 * Score storage behind an interface.
 *
 * The dev driver writes JSON and blobs to disk so the whole stack runs with
 * zero external services. Production (PLAN.md: Postgres + S3-compatible
 * object storage on CubCloud infra) implements the same interface; nothing
 * above this file changes.
 */
import { mkdir, readdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { createHash, randomBytes } from "node:crypto";
import path from "node:path";

export interface SharedScore {
  id: string;
  title: string;
  artist: string;
  format: "gp" | "altex";
  /** alphaTex source, for scores that have one. */
  tex: string | null;
  /** Base64 of the original binary, for imported Guitar Pro files. */
  bytesB64: string | null;
  createdAt: number;
  /** Absent on shares created before accounts existed, or anonymously. */
  ownerId?: string;
}

/** What a share list needs. Never the body: see FileStore.listByOwner. */
export interface ShareSummary {
  id: string;
  title: string;
  artist: string;
  createdAt: number;
}

export interface ScoreStore {
  put(record: SharedScore): Promise<void>;
  get(id: string): Promise<SharedScore | undefined>;
  delete(id: string): Promise<void>;
  listByOwner(ownerId: string): Promise<ShareSummary[]>;
}

export interface User {
  id: string;
  email: string;
  passwordHash: string;
  createdAt: number;
}

export interface UserStore {
  byEmail(email: string): Promise<User | undefined>;
  byId(id: string): Promise<User | undefined>;
  put(user: User): Promise<void>;
  /**
   * Binds an email to a user id, or fails because someone else already holds
   * it. Registration needs one indivisible step here: a check followed by a
   * write lets two simultaneous signups both pass the check and create two
   * accounts for one address, and only one of them can ever log in.
   */
  claimEmail(email: string, userId: string): Promise<boolean>;
}

export interface SessionStore {
  create(token: string, userId: string): Promise<void>;
  userIdFor(token: string): Promise<string | undefined>;
  destroy(token: string): Promise<void>;
}

/** A user's cloud library entry. Bytes travel as base64 in the JSON body. */
export interface CloudEntry {
  id: string;
  ownerId: string;
  title: string;
  artist: string;
  format: "gp" | "altex";
  tex: string | null;
  bytesB64: string | null;
  /** Semantic model JSON for scores authored or converted in CubScore. */
  core: string | null;
  report: string | null;
  authored: boolean;
  tracks: number;
  bars: number;
  addedAt: number;
  updatedAt: number;
}

/** What one account is currently taking up. */
export interface Usage {
  entries: number;
  bytes: number;
}

export interface LibraryStore {
  put(entry: CloudEntry): Promise<void>;
  get(ownerId: string, id: string): Promise<CloudEntry | undefined>;
  list(ownerId: string): Promise<CloudEntry[]>;
  delete(ownerId: string, id: string): Promise<void>;
  /** Measured from file sizes, so it costs no reads and no parsing. */
  usage(ownerId: string): Promise<Usage>;
}

/** Unguessable id: share links are capability URLs until accounts land. */
export function newShareId(): string {
  return randomBytes(12).toString("base64url");
}

function assertSafeId(id: string): void {
  // Ids are generated by us, but never trust them as paths.
  if (!/^[A-Za-z0-9_-]{1,64}$/.test(id)) throw new Error("invalid id");
}

/** One JSON document per record in a directory. */
class JsonDir<T extends { id: string }> {
  constructor(private readonly dir: string) {}

  private fileFor(id: string): string {
    assertSafeId(id);
    return path.join(this.dir, `${id}.json`);
  }

  /**
   * Write to a temporary name, then rename over the target.
   *
   * writeFile truncates first, so a crash or a full disk mid-write leaves a
   * half-written record where a whole one used to be. rename is atomic within
   * a filesystem: a reader sees the old record or the new one, never a
   * fragment. The .tmp suffix keeps casualties out of all(), which only reads
   * names ending in .json.
   */
  async put(record: T): Promise<void> {
    await mkdir(this.dir, { recursive: true });
    const file = this.fileFor(record.id);
    const temp = `${file}.${randomBytes(6).toString("hex")}.tmp`;
    try {
      await writeFile(temp, JSON.stringify(record));
      await rename(temp, file);
    } catch (e) {
      await rm(temp, { force: true }).catch(() => undefined);
      throw e;
    }
  }

  /** Exclusive create. False means the key was already claimed. */
  async claim(id: string, record: T): Promise<boolean> {
    await mkdir(this.dir, { recursive: true });
    try {
      await writeFile(this.fileFor(id), JSON.stringify(record), { flag: "wx" });
      return true;
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "EEXIST") return false;
      throw e;
    }
  }

  async get(id: string): Promise<T | undefined> {
    let raw: string;
    try {
      raw = await readFile(this.fileFor(id), "utf8");
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") return undefined;
      if ((e as Error).message === "invalid id") return undefined;
      throw e;
    }
    try {
      return JSON.parse(raw) as T;
    } catch {
      // Damage stays with the damaged record. This used to throw, and because
      // finding a user by email scanned every user file, one unparseable
      // record failed every login on the server rather than just its own.
      console.error(`cubscore: ignoring unreadable record ${this.fileFor(id)}`);
      return undefined;
    }
  }

  async delete(id: string): Promise<void> {
    try {
      await rm(this.fileFor(id));
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e;
    }
  }

  async all(): Promise<T[]> {
    return this.collect((record) => record);
  }

  /**
   * Reads one record at a time, keeping only what `pick` returns.
   *
   * all() built an array of every record first. For shares that means every
   * base64 body — up to 24 MB each — resident at once, so a few hundred shared
   * Guitar Pro files turned one signed-in user opening the account panel into
   * gigabytes in a single request. Filtering as it reads keeps the peak at one
   * record.
   */
  async collect<R>(pick: (record: T) => R | undefined): Promise<R[]> {
    let names: string[];
    try {
      names = (await readdir(this.dir)).filter((n) => n.endsWith(".json"));
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") return [];
      throw e;
    }
    const out: R[] = [];
    for (const name of names) {
      const record = await this.get(name.slice(0, -5));
      if (!record) continue;
      const kept = pick(record);
      if (kept !== undefined) out.push(kept);
    }
    return out;
  }
}

export class FileStore implements ScoreStore {
  private readonly docs: JsonDir<SharedScore>;

  constructor(dir: string) {
    this.docs = new JsonDir<SharedScore>(dir);
  }

  put(record: SharedScore): Promise<void> {
    return this.docs.put(record);
  }

  get(id: string): Promise<SharedScore | undefined> {
    return this.docs.get(id);
  }

  delete(id: string): Promise<void> {
    return this.docs.delete(id);
  }

  /**
   * Linear scan; fine for the dev driver, an indexed query in production. Only
   * the metadata is retained, because that is all the caller sends and the
   * bodies are what would exhaust memory.
   */
  async listByOwner(ownerId: string): Promise<ShareSummary[]> {
    const mine = await this.docs.collect((s) =>
      s.ownerId === ownerId
        ? { id: s.id, title: s.title, artist: s.artist, createdAt: s.createdAt }
        : undefined,
    );
    return mine.sort((a, b) => b.createdAt - a.createdAt);
  }
}

export class FileUserStore implements UserStore {
  private readonly docs: JsonDir<User>;
  /** email -> user id, so a login is two reads rather than a full scan. */
  private readonly emails: JsonDir<{ id: string; userId: string }>;

  constructor(dir: string) {
    this.docs = new JsonDir<User>(dir);
    this.emails = new JsonDir(path.join(dir, "by-email"));
  }

  /** Emails are not filename-safe, and hashing keeps them out of directory listings. */
  private static key(email: string): string {
    return createHash("sha256").update(email).digest("hex").slice(0, 32);
  }

  put(user: User): Promise<void> {
    return this.docs.put(user);
  }

  byId(id: string): Promise<User | undefined> {
    return this.docs.get(id);
  }

  /**
   * Claims an address, and takes over a pointer whose user has gone.
   *
   * Without the takeover a single unreadable user record was a permanent
   * lockout: the pointer resolved to nothing, so login answered "invalid email
   * or password", and the exclusive claim meant the address could never be
   * registered again — not by the user, not by support.
   */
  async claimEmail(email: string, userId: string): Promise<boolean> {
    const key = FileUserStore.key(email);
    if (await this.emails.claim(key, { id: key, userId })) return true;
    const existing = await this.emails.get(key);
    if (existing && (await this.docs.get(existing.userId))) return false;
    await this.emails.put({ id: key, userId });
    return true;
  }

  byEmail(email: string): Promise<User | undefined> {
    // Index only. This used to fall back to reading every user record when the
    // address was not indexed, which meant any unknown address — a fresh random
    // one on every request, so no per-address limit applied — cost one file read
    // per account on the server. A few thousand requests took the API down for
    // everyone. Records written before the index exists are migrated at boot;
    // see indexExistingEmails.
    return this.emails
      .get(FileUserStore.key(email))
      .then((pointer) => (pointer ? this.docs.get(pointer.userId) : undefined));
  }

  /**
   * Gives every user record an index entry, once, at startup.
   *
   * This is the migration that replaces the per-login fallback scan: it costs
   * one pass over the accounts when the process starts rather than one pass per
   * unrecognised login attempt forever.
   */
  async indexExistingEmails(): Promise<number> {
    let added = 0;
    for (const user of await this.docs.all()) {
      const key = FileUserStore.key(user.email);
      if (await this.emails.claim(key, { id: key, userId: user.id })) added += 1;
    }
    return added;
  }
}

export class FileSessionStore implements SessionStore {
  private readonly docs: JsonDir<{ id: string; userId: string; createdAt: number }>;

  /**
   * @param maxAgeMs How long a session stays valid. The cookie's Max-Age is a
   * hint the client may ignore; this is the part that is enforced. Without it a
   * token that leaked any other way — a proxy log, a backup, a copied browser
   * profile, the data directory itself — authenticated forever.
   */
  constructor(dir: string, private readonly maxAgeMs: number) {
    this.docs = new JsonDir(dir);
  }

  create(token: string, userId: string): Promise<void> {
    return this.docs.put({ id: token, userId, createdAt: Date.now() });
  }

  async userIdFor(token: string): Promise<string | undefined> {
    const session = await this.docs.get(token);
    if (!session) return undefined;
    if (Date.now() - session.createdAt > this.maxAgeMs) {
      // Expired sessions are cleaned up as they are presented, which keeps the
      // directory from growing one file per login forever.
      await this.docs.delete(token);
      return undefined;
    }
    return session.userId;
  }

  destroy(token: string): Promise<void> {
    return this.docs.delete(token);
  }
}

export class FileLibraryStore implements LibraryStore {
  constructor(private readonly dir: string) {}

  private dirFor(ownerId: string): JsonDir<CloudEntry> {
    assertSafeId(ownerId);
    return new JsonDir<CloudEntry>(path.join(this.dir, ownerId));
  }

  put(entry: CloudEntry): Promise<void> {
    return this.dirFor(entry.ownerId).put(entry);
  }

  get(ownerId: string, id: string): Promise<CloudEntry | undefined> {
    return this.dirFor(ownerId).get(id);
  }

  async list(ownerId: string): Promise<CloudEntry[]> {
    const all = await this.dirFor(ownerId).all();
    return all.sort((a, b) => b.updatedAt - a.updatedAt);
  }

  delete(ownerId: string, id: string): Promise<void> {
    return this.dirFor(ownerId).delete(id);
  }

  /**
   * Counts and measures an account's entries without reading any of them.
   *
   * Nothing bounded how much one account could store: 600 writes an hour at 24
   * MB each, and registration is free, so filling the disk cost an attacker
   * nothing and every real user's autosave and sync then failed with ENOSPC.
   * Sizes come from stat rather than from the records, so a large library costs
   * one syscall per entry instead of parsing megabytes of base64.
   */
  async usage(ownerId: string): Promise<Usage> {
    assertSafeId(ownerId);
    const dir = path.join(this.dir, ownerId);
    let names: string[];
    try {
      names = (await readdir(dir)).filter((n) => n.endsWith(".json"));
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") return { entries: 0, bytes: 0 };
      throw e;
    }
    let bytes = 0;
    for (const name of names) {
      try {
        bytes += (await stat(path.join(dir, name))).size;
      } catch {
        // Removed between the listing and the stat; it is not taking up space.
      }
    }
    return { entries: names.length, bytes };
  }
}
