/**
 * Score storage behind an interface.
 *
 * The dev driver writes JSON and blobs to disk so the whole stack runs with
 * zero external services. Production (PLAN.md: Postgres + S3-compatible
 * object storage on CubCloud infra) implements the same interface; nothing
 * above this file changes.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import path from "node:path";

export interface SharedScore {
  id: string;
  title: string;
  artist: string;
  format: "gp" | "altex";
  /** alphaTex source, for scores that have one. */
  tex: string | null;
  /** Base64 of the original binary, for imported Guitar Pro files. */
  bytesB64: string | null;
  createdAt: number;
}

export interface ScoreStore {
  put(record: SharedScore): Promise<void>;
  get(id: string): Promise<SharedScore | undefined>;
}

/** Unguessable id: share links are capability URLs until accounts land. */
export function newShareId(): string {
  return randomBytes(12).toString("base64url");
}

export class FileStore implements ScoreStore {
  constructor(private readonly dir: string) {}

  private fileFor(id: string): string {
    // Ids are generated by us, but never trust them as paths.
    if (!/^[A-Za-z0-9_-]{1,64}$/.test(id)) throw new Error("invalid id");
    return path.join(this.dir, `${id}.json`);
  }

  async put(record: SharedScore): Promise<void> {
    await mkdir(this.dir, { recursive: true });
    await writeFile(this.fileFor(record.id), JSON.stringify(record));
  }

  async get(id: string): Promise<SharedScore | undefined> {
    try {
      return JSON.parse(await readFile(this.fileFor(id), "utf8")) as SharedScore;
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") return undefined;
      if ((e as Error).message === "invalid id") return undefined;
      throw e;
    }
  }
}
